name: hospital_flutter
description: Hospital Management Flutter Application

publish_to: 'none'

version: 1.3.3+133

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.2.0
  shared_preferences: ^2.2.2
  path: ^1.9.0
  crypto: ^3.0.5

  # Update system
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0

  # Database
  sqflite: ^2.0.0+3

  # UI
  cupertino_icons: ^1.0.8

  rename: ^3.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
